[build]
  command = "npm install --prefix server && npm install --prefix client && npm run build --prefix client"
  functions = "server/functions"
  publish   = "client/dist"

[dev]
  command    = "npm run dev --prefix client"  
  targetPort = 5173                            
  port       = 8888   

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200