[build]
  functions = "server/functions"
  command   = "npm install && npm run build --prefix client"
  publish   = "client/dist"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200