[build]
  command = "npm install --prefix server && npm install --prefix client && npm run build --prefix client"
  functions = "server/functions"
  publish   = "client/dist"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200